export enum TypeAccount {
    SAVING_ACCOUNT = 'SAVING_ACCOUNT',
    CHEKING_ACCOUNT = 'CHEKING_ACCOUNT',


    
    INVESTMENT = 'INVESTMENT',
    AUTO_TRANSFER = 'AUTO_TRANSFER',
    INCOME = 'INCOME',
    LOAN = 'LOAN',
    RETURN_LOAN = 'RETURN_LOAN',
    RETURN_INVESTMENT = 'RETURN_INVESTMENT'
}