export enum TypeTransaction {
    TRANSFER = 'TRANSFER',
    DEPOSIT = 'DEPOSIT',
    INVESTMENT = 'INVESTMENT',
    AUTO_TRANSFER = 'AUTO_TRANSFER',
    INCOME = 'INCOME',
    LOAN = 'LOAN',
    RETURN_LOAN = 'RETURN_LOAN',
    RETURN_INVESTMENT = 'RETURN_INVESTMENT'
}